export const CountryLocales = {
    AT: "de_AT",
    BE: "nl_BE",
    BG: "bg_BG",
    HR: "hr_HR",
    CY: "el_CY",
    CZ: "cs_CZ",
    DK: "da_DK",
    EE: "et_EE",
    FI: "fi_FI",
    FR: "fr_FR",
    DE: "de_DE",
    GR: "el_GR",
    HU: "hu_HU",
    IE: "en_IE",
    IT: "it_IT",
    LV: "lv_LV",
    LT: "lt_LT",
    LU: "fr_LU",
    MT: "mt_MT",
    NL: "nl_NL",
    PL: "pl_PL",
    PT: "pt_PT",
    RO: "ro_RO",
    SK: "sk_SK",
    SI: "sl_SI",
    ES: "es_ES",
    SE: "sv_SE",
} as const;

export const CountryCurrencies = {
    AT: { currency: "eur", currency_sumbol: "€" },
    BE: { currency: "eur", currency_sumbol: "€" },
    BG: { currency: "bgn", currency_sumbol: "лв" },
    HR: { currency: "eur", currency_sumbol: "€" },
    CY: { currency: "eur", currency_sumbol: "€" },
    CZ: { currency: "czk", currency_sumbol: "Kč" },
    DK: { currency: "dkk", currency_sumbol: "kr" },
    EE: { currency: "eur", currency_sumbol: "€" },
    FI: { currency: "eur", currency_sumbol: "€" },
    FR: { currency: "eur", currency_sumbol: "€" },
    DE: { currency: "eur", currency_sumbol: "€" },
    GR: { currency: "eur", currency_sumbol: "€" },
    HU: { currency: "huf", currency_sumbol: "Ft" },
    IE: { currency: "eur", currency_sumbol: "€" },
    IT: { currency: "eur", currency_sumbol: "€" },
    LV: { currency: "eur", currency_sumbol: "€" },
    LT: { currency: "eur", currency_sumbol: "€" },
    LU: { currency: "eur", currency_sumbol: "€" },
    MT: { currency: "eur", currency_sumbol: "€" },
    NL: { currency: "eur", currency_sumbol: "€" },
    PL: { currency: "pln", currency_sumbol: "zł" },
    PT: { currency: "eur", currency_sumbol: "€" },
    RO: { currency: "ron", currency_sumbol: "lei" },
    SK: { currency: "eur", currency_sumbol: "€" },
    SI: { currency: "eur", currency_sumbol: "€" },
    ES: { currency: "eur", currency_sumbol: "€" },
    SE: { currency: "sek", currency_sumbol: "kr" },
} as const;

