import { ColorIndicator, SafetyLevel } from '../../src/generated/prisma';

export type IngredientSeedEntry = {
    name: string;
    synonyms?: string[];
    scientific_name?: string;
    ai_summary: string;
    benefits?: string;
    risks?: string;
    purpose?: string;
    pregnancy_safety?: SafetyLevel;
    color_indicator: ColorIndicator;
    overall_score: number;
    safety_score: number;
    is_vegan?: boolean;
    is_cruelty_free?: boolean;
};

export const INGREDIENT_SEED: IngredientSeedEntry[] = [
    {
        name: 'Water',
        scientific_name: 'Aqua',
        ai_summary: 'Universal solvent and base for most cosmetic and food formulations.',
        benefits: 'Hydrates and carries other ingredients.',
        purpose: 'Solvent and base',
        pregnancy_safety: SafetyLevel.SAFE,
        color_indicator: ColorIndicator.VERY_SAFE,
        overall_score: 20,
        safety_score: 20,
        is_vegan: true,
        is_cruelty_free: true,
    },
    {
        name: 'Glycerin',
        synonyms: ['Glycerol'],
        ai_summary: 'Humectant that draws moisture into the skin.',
        benefits: 'Hydration and skin barrier support.',
        risks: 'Rare irritation in very high concentrations.',
        purpose: 'Humectant',
        pregnancy_safety: SafetyLevel.SAFE,
        color_indicator: ColorIndicator.VERY_SAFE,
        overall_score: 18.5,
        safety_score: 18,
        is_vegan: true,
    },
    {
        name: 'Niacinamide',
        synonyms: ['Vitamin B3', 'Nicotinamide'],
        ai_summary: 'Versatile active for barrier support, oil control, and tone evening.',
        benefits: 'Reduces redness, strengthens barrier, minimizes pores appearance.',
        risks: 'Mild flushing possible at very high concentrations.',
        purpose: 'Active / anti-inflammatory',
        pregnancy_safety: SafetyLevel.SAFE,
        color_indicator: ColorIndicator.SAFE,
        overall_score: 17.5,
        safety_score: 17,
        is_vegan: true,
        is_cruelty_free: true,
    },
    {
        name: 'Hyaluronic Acid',
        synonyms: ['Sodium Hyaluronate'],
        ai_summary: 'Powerful humectant holding up to 1000x its weight in water.',
        benefits: 'Plumps and hydrates skin.',
        purpose: 'Humectant',
        pregnancy_safety: SafetyLevel.SAFE,
        color_indicator: ColorIndicator.VERY_SAFE,
        overall_score: 18,
        safety_score: 18,
        is_vegan: true,
    },
    {
        name: 'Retinol',
        synonyms: ['Vitamin A'],
        ai_summary: 'Gold-standard anti-aging active; increases cell turnover.',
        benefits: 'Reduces fine lines, improves texture.',
        risks: 'Irritation, photosensitivity; avoid in pregnancy.',
        purpose: 'Anti-aging active',
        pregnancy_safety: SafetyLevel.AVOID,
        color_indicator: ColorIndicator.CAUTION,
        overall_score: 12,
        safety_score: 10,
        is_vegan: true,
    },
    {
        name: 'Salicylic Acid',
        synonyms: ['BHA'],
        ai_summary: 'Oil-soluble exfoliant effective for acne and clogged pores.',
        benefits: 'Unclogs pores, reduces breakouts.',
        risks: 'Dryness and irritation; caution during pregnancy.',
        purpose: 'Exfoliant / acne treatment',
        pregnancy_safety: SafetyLevel.CAUTION,
        color_indicator: ColorIndicator.MODERATE,
        overall_score: 14,
        safety_score: 13,
    },
    {
        name: 'Fragrance',
        synonyms: ['Parfum'],
        ai_summary: 'Blend of aromatic compounds; common allergen and irritant.',
        benefits: 'Product scent.',
        risks: 'Allergic reactions, sensitization, especially for sensitive skin.',
        purpose: 'Fragrance',
        pregnancy_safety: SafetyLevel.CAUTION,
        color_indicator: ColorIndicator.HIGH_RISK,
        overall_score: 6,
        safety_score: 5,
    },
    {
        name: 'Parabens',
        synonyms: ['Methylparaben', 'Propylparaben'],
        ai_summary: 'Preservative family with debated hormone-disruption concerns.',
        benefits: 'Prevents microbial growth.',
        risks: 'Potential endocrine disruption at high exposure.',
        purpose: 'Preservative',
        pregnancy_safety: SafetyLevel.CAUTION,
        color_indicator: ColorIndicator.CAUTION,
        overall_score: 9,
        safety_score: 8,
    },
    {
        name: 'Coconut Oil',
        scientific_name: 'Cocos Nucifera Oil',
        ai_summary: 'Occlusive plant oil; highly comedogenic for some skin types.',
        benefits: 'Moisturizing and antimicrobial properties.',
        risks: 'Can clog pores; not ideal for acne-prone skin.',
        purpose: 'Emollient',
        pregnancy_safety: SafetyLevel.SAFE,
        color_indicator: ColorIndicator.MODERATE,
        overall_score: 13,
        safety_score: 12,
        is_vegan: true,
    },
    {
        name: 'Ceramides',
        ai_summary: 'Lipids that restore and maintain the skin barrier.',
        benefits: 'Barrier repair, reduced transepidermal water loss.',
        purpose: 'Barrier repair',
        pregnancy_safety: SafetyLevel.SAFE,
        color_indicator: ColorIndicator.VERY_SAFE,
        overall_score: 19,
        safety_score: 19,
        is_vegan: false,
    },
    {
        name: 'Ascorbic Acid',
        synonyms: ['Vitamin C'],
        ai_summary: 'Antioxidant brightening active; unstable in some formulations.',
        benefits: 'Brightening, collagen support, antioxidant protection.',
        risks: 'Stinging on sensitive skin; oxidizes easily.',
        purpose: 'Antioxidant / brightening',
        pregnancy_safety: SafetyLevel.SAFE,
        color_indicator: ColorIndicator.SAFE,
        overall_score: 16,
        safety_score: 15,
        is_vegan: true,
    },
    {
        name: 'Dimethicone',
        ai_summary: 'Silicone that provides smooth slip and occlusive protection.',
        benefits: 'Smooths texture, locks in moisture.',
        risks: 'Can feel heavy; environmental persistence concerns.',
        purpose: 'Emollient / silicone',
        pregnancy_safety: SafetyLevel.SAFE,
        color_indicator: ColorIndicator.SAFE,
        overall_score: 15,
        safety_score: 14,
        is_vegan: true,
    },
    {
        name: 'Phenoxyethanol',
        ai_summary: 'Widely used preservative; generally safe at low concentrations.',
        benefits: 'Broad antimicrobial preservation.',
        risks: 'Irritation at higher concentrations.',
        purpose: 'Preservative',
        pregnancy_safety: SafetyLevel.CAUTION,
        color_indicator: ColorIndicator.MODERATE,
        overall_score: 12.5,
        safety_score: 12,
    },
    {
        name: 'Aloe Vera',
        scientific_name: 'Aloe Barbadensis Leaf Juice',
        ai_summary: 'Soothing botanical with anti-inflammatory properties.',
        benefits: 'Calms irritation, light hydration.',
        purpose: 'Soothing agent',
        pregnancy_safety: SafetyLevel.SAFE,
        color_indicator: ColorIndicator.VERY_SAFE,
        overall_score: 17,
        safety_score: 17,
        is_vegan: true,
    },
    {
        name: 'Titanium Dioxide',
        ai_summary: 'Mineral UV filter and white pigment.',
        benefits: 'Broad-spectrum UV protection.',
        risks: 'Generally well tolerated; inhalation concerns in powder form.',
        purpose: 'UV filter / pigment',
        pregnancy_safety: SafetyLevel.SAFE,
        color_indicator: ColorIndicator.SAFE,
        overall_score: 16.5,
        safety_score: 16,
        is_vegan: true,
    },
];
